version: '3.9'
x-omnistrate-integrations:
  - omnistrateLogging
  - omnistrateMetrics
services:
  SaaSBuilder:
    image: sharmaamits/saasbuilder:1.0.11
    ports:
      - '8080:8080'
    environment:
      - PROVIDER_EMAIL=$var.providerEmail
      - PROVIDER_PASSWORD=$var.providerPassword
      - YOUR_SAAS_DOMAIN_URL=$sys.network.externalClusterEndpoint
      - MAIL_USER_EMAIL=$var.senderEmail
      - MAIL_USER_PASSWORD=$var.senderPassword
      - MAIL_FROM=$var.senderFrom
      - GOOGLE_ANALYTICS_TAG_ID=$var.googleAnalyticsTagID
      - MAIL_PROVIDER=$var.mailProvider
      - MAIL_SMTP_SERVICE=$var.mailSmtpService
      - MAIL_SMTP_HOST=$var.mailSmtpHost
      - MAIL_SMTP_PORT=$var.mailSmtpPort
    x-omnistrate-compute:
      instanceTypes:
        - cloudProvider: aws
          apiParam: instanceType
        - cloudProvider: gcp
          apiParam: instanceType
    x-omnistrate-capabilities:
      httpReverseProxy:
        targetPort: 8080
      enableMultiZone: true
      autoscaling:
        maxReplicas: 10
        minReplicas: 2
        idleMinutesBeforeScalingDown: 2
        idleThreshold: 20
        overUtilizedMinutesBeforeScalingUp: 3
        overUtilizedThreshold: 80
    x-omnistrate-api-params:
      - key: instanceType
        description: Instance Type
        name: Instance Type
        type: String
        modifiable: true
        required: true
        export: true
      - key: providerEmail
        description: Service provider Omnistrate email address
        name: Omnistrate email
        type: String
        modifiable: true
        required: true
        export: true
      - key: providerPassword
        description: Service provider Omnistrate account password
        name: Omnistrate password
        type: String
        modifiable: true
        required: true
        export: false
      - key: senderEmail
        description: email address to login to the SMTS provider
        name: SMTS email address
        type: String
        modifiable: true
        required: true
        export: true
      - key: senderPassword
        description: Password to authorize against the SMTS provider
        name: SMTS password
        type: String
        modifiable: true
        required: true
        export: false
      - key: senderFrom
        description: email address from the field From to communicate to customers
        name: Email address
        type: String
        modifiable: true
        required: false
        export: true  
      - key: googleAnalyticsTagID
        description: Google Analytics tag ID
        name: Google Analytics tag ID
        type: String
        modifiable: true
        required: false
        export: true        
      - key: mailProvider
        description: Mail provider
        name: Mail provider
        type: String
        modifiable: true
        required: true
        export: true
        defaultValue: gmail
      - key: mailSmtpService
        description: SMTP service
        name: SMTP service
        type: String
        modifiable: true
        required: true
        export: true
        defaultValue: gmail
      - key: mailSmtpHost
        description: SMTP host
        name: SMTP host
        type: String
        modifiable: true
        required: true
        export: true
        defaultValue: smtp.gmail.com
      - key: mailSmtpPort
        description: SMTP port
        name: SMTP port
        type: String
        modifiable: true
        required: true
        export: true
        defaultValue: 587