// AUTO-GENERATED by `yarn icons:build` from src/icons/svg/arrow-up-right.svg. Do not edit.
import { createIcon } from "./createIcon";

export default createIcon({
  name: "ArrowUpRight",
  viewBox: "0 0 20 20",
  strokeWidth: 1.66667,
  children: (
    <>
      <path
        d="M5.8335 14.1667L14.1668 5.83337M14.1668 14.1667V5.83337H5.8335"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </>
  ),
});
