// AUTO-GENERATED by `yarn icons:build` from src/icons/svg/bar-chart-01.svg. Do not edit.
import { createIcon } from "./createIcon";

export default createIcon({
  name: "BarChart01",
  viewBox: "0 0 24 24",
  strokeWidth: 1.5,
  children: (
    <>
      <path d="M18 20V10M12 20V4M6 20V14" strokeLinecap="round" strokeLinejoin="round" />
    </>
  ),
});
