// AUTO-GENERATED by `yarn icons:build` from src/icons/svg/flip-backward.svg. Do not edit.
import { createIcon } from "./createIcon";

export default createIcon({
  name: "FlipBackward",
  viewBox: "0 0 20 20",
  strokeWidth: 1.66667,
  children: (
    <>
      <path
        d="M2.5 7.5H13.75C15.82108 7.5 17.5 9.17892 17.5 11.25C17.5 13.32108 15.82108 15 13.75 15H10M2.5 7.5L5.83333 4.16667M2.5 7.5L5.83333 10.83333"
        strokeLinecap="round"
        strokeLinejoin="round"
      />
    </>
  ),
});
