name: Build

env: 
    NODE_VERSION: 20

on:
  push:
    branches: 
        - master
  pull_request:
    branches: 
        - master
  release:
    types:
        - published

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:

    lint:
        runs-on: ubuntu-latest
        permissions:
            checks: write
            contents: write          
    
        steps:
        - name: Checkout code
          uses: actions/checkout@v3
    
        - name: Set up Node.js
          uses: actions/setup-node@v3
          with:
            node-version: ${{ env.NODE_VERSION }}
    
        - name: Install dependencies
          run: yarn install
    
        - name: Run linters
          uses: wearerequired/lint-action@v2
          with:
            eslint: true

    build:
        runs-on: ubuntu-latest
    
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
    
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: ${{ env.NODE_VERSION }}
    
            - name: Install dependencies
              run: yarn install
    
            - name: Build project
              run: yarn build
              
    publish:
        name: "create tag"
        if: github.event_name == 'push'
        needs: [lint, build]
        runs-on: ubuntu-latest
        permissions:
            contents: write
        concurrency:
            group: Publish-'${{ github.workflow }}'
        steps: 
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Bump version and push tag
              id: tag_version
              uses: mathieudutour/github-tag-action@v6.1
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                
