name: Playwright Tests - SaaSBuilder
permissions:
  contents: read
  actions: write

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened]
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for running tests"
        required: false
        default: "Manual trigger"

jobs:
  test:
    name: Playwright Tests - SaaSBuilder
    if: github.event.pull_request.draft == false
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Skip Playwright tests
        run: echo "Playwright tests are temporarily skipped."
